Repository ErrorCode-510/PandaOffice_back, pull requests merged in 2024-06, with the labels that each got.

#10 채용/면접 엔티티 컬럼 주석 완료
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/Applicant.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/Place.java
Labels: 기능구현잇슈, 성우현

#13 Feature/6 notice entity
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/Notice.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/NoticeImage.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/template.java
Labels: 기능구현잇슈, 김민준

#14 Feature/1 welfare entity
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/Category.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/ReplyRecord.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/Survey.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/SurveyQuestion.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/template.java
Labels: 기능구현잇슈, 신동우

#19 #1 feat e_approval
  DB/script.sql
  build.gradle
  src/main/java/com/errorCode/pandaOffice/PandaOfficeApplication.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLine.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/AutoApprovalLine.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/AutoApprovalLineFolder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/AutoApprovalLineOrder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DepartmentBox.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DepartmentDocument.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/Document.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentAttachedFile.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplate.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplateFolder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApproveState.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApproveType.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/template.java
Labels: 기능구현잇슈, 편승준

#26 Feature/3 member entity
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/CareerHistory.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Department.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/EducationHistory.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/EmployeePhoto.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/FamilyMember.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Hobby.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Job.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/License.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/response/EmployeeDTO.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/response/template.java
Labels: 기능구현잇슈

#30 [기능구현] 전자결재, 연차 도메인 간 엔티티 매핑 오류 수정
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalDocument.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/Document.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/License.java
Labels: 기능구현잇슈, 편승준

#35 [기능구현] 사원 & 급여관리 엔티티 수정
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/DeductionRecord.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/EarningRecord.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/PayrollRecord.java
  src/main/java/com/errorCode/pandaOffice/payroll/service/PayrollService.java
  src/main/java/com/errorCode/pandaOffice/payroll/service/Service.java
Labels: 기능구현잇슈, 이유란

#37 [기능구현] 전자결재 다중 조건 검색 api구현 및 사원 도메인 엔티티 getter 작성
  DB/ApprovalDocumentDummy.sql
  http/document-test.http
  src/main/java/com/errorCode/pandaOffice/PandaOfficeApplication.java
  src/main/java/com/errorCode/pandaOffice/common/paging/Pagination.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalDocument.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplateFolder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalDocumentRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalDocumentSpecification.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/template.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApproveState.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApproveType.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/response/ApproveDocumentListResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/response/template.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/Controller.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentService.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/Service.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/CareerHistory.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Department.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/EducationHistory.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/EmployeePhoto.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/FamilyMember.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Hobby.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Job.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/License.java
Labels: 기능구현잇슈, 편승준

#44 Feature/42 entity
  http/Recruitment.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/repository/ApplicantRepository.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/ApplicantResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/template.java
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/Controller.java
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/RecruitmentController.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/RecruitmentService.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/Service.java
  src/main/resources/application.yml
Labels: 성우현, 기능설계햇슈

#51 [기능구현] 사원 엔티티 연봉 추가
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
Labels: 기능구현잇슈, 이유란

#52 [기능구현] 토큰에서 사번 가져오기 기능 구현
  build.gradle
  http/document-test.http
  http/login-test.http
  src/main/java/com/errorCode/devContents/PasswordMaker.java
  src/main/java/com/errorCode/pandaOffice/auth/config/SecurityConfig.java
  src/main/java/com/errorCode/pandaOffice/auth/type/CustomUser.java
  src/main/java/com/errorCode/pandaOffice/auth/util/TokenUtils.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalDocument.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLine.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLineTemplate.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLineTemplateFolder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLineTemplateOrder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/AutoApprovalLine.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentAttachedFile.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplate.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalDocumentRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalLineRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalLineTemplateFolderRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalLineTemplateOrderRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalLineTemplateRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/AutoApprovalLineRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DepartmentBoxRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DepartmentDocumentRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DocumentAttachedFileRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DocumentTemplateFolderRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DocumentTemplateRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/specification/ApprovalDocumentSpecification.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApprovalStatus.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApproveState.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApproveType.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/converter/ApprovalStatusConverter.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/converter/ApprovalTypeConverter.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/ApprovalDocument/ApprovalDocumentDetailResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/ApprovalDocument/ApprovalDocumentListResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/ApprovalDocument/ApprovalLine/CreateApprovalLineRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/ApprovalDocument/CreateApprovalDocumentRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/ApprovalDocument/UpdateApprovalDocumentRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/request/template.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentService.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/EmployeeRepository.java
  src/main/resources/application.yml
Labels: 기능구현잇슈, 편승준

#53 [기능구현] 암호화된 비밀번호 DB 추가 및 오류 수정
  DB/ApprovalDocumentDummy.sql
  DB/Dummy.sql
  http/document-test.http
  http/login-test.http
  src/main/java/com/errorCode/devContents/PasswordMaker.java
  src/main/java/com/errorCode/pandaOffice/PandaOfficeApplication.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentController.java
Labels: 기능구현잇슈, 편승준

#57 Feature/43 create attendance status page 급한 오류 수정
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveCategoryRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AttendanceRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/OvertimeRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/presectation/AttendanceController.java
  src/main/java/com/errorCode/pandaOffice/attendance/service/AttendanceService.java
Labels: 버그잇슈

#61 [기능설계] 면접자 조건 검색 구현
  DB/Dummy.sql
  http/Recruitment.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/Applicant.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/repository/ApplicantRepository.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/ApplicantCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/InterviewScheduleCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/template.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/InterviewScheduleResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/PlaceResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/RecruitmentController.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/RecruitmentService.java
Labels: 기능구현잇슈, 성우현

#62 [기능수정]설문 엔티티 수정 및 dto, repository 작성
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/Category.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/ReplyRecord.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/Survey.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/SurveyCategory.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/SurveyQuestion.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/ReplyRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/SurveyCategoryRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/SurveyQuestionRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/SurveyRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/template.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/ReplyRecordDTO.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/SurveyCategoryDTO.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/SurveyDTO.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/SurveyQuestionDTO.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/template.java
  src/main/java/com/errorCode/pandaOffice/welfare/presectation/SurveyController.java
  src/main/java/com/errorCode/pandaOffice/welfare/service/SurveyService.java
Labels: 기능구현잇슈, 신동우

#74 [기능구현] 면접일정 등록 구현 및 채용/면접 더미, http 추가
  DB/recruitment-dummy.sql
  http/Recruitment.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/repository/ApplicantRepository.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/ApplicantRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/InterviewScheduleCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/InterviewScheduleResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/RecruitmentController.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/RecruitmentService.java
Labels: 기능구현잇슈, 성우현

#76 [기능구현] 면접일정 상세 조회 구현
  http/Recruitment.http
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/RecruitmentController.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/RecruitmentService.java
Labels: 기능구현잇슈, 성우현

#78 [기능구현] 결재 양식과 자동 결재선, 폴더 API 구현
  DB/Document.sql
  http/document-test.http
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLine.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLineTemplate.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLineTemplateOrder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/AutoApprovalLine.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplate.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplateFolder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DocumentTemplateFolderRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DocumentTemplateRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/ApprovalDocument/ApprovalLine/CreateApprovalLineRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/ApprovalDocument/CreateApprovalDocumentRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/ApprovalDocumentFolderResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/ApprovalDocumentTemplateResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/CreateApprovalDocumentFolderRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/CreateApprovalDocumentTemplateRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/DeleteApprovalDocumentFolderRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/UpdateApprovalDocumentTemplateRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentTemplateController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentService.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentTemplateService.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/EmployeeRepository.java
  src/main/resources/application.yml
Labels: 기능구현잇슈, 편승준

#79 [기능구현] 공지사항 등록 구현
  build.gradle
  http/notice-test.http
  src/main/java/com/errorCode/pandaOffice/auth/config/SecurityConfig.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/Notice.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/NoticeImage.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/repository/NoticeRepository.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/repository/template.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/request/NoticeRequestDTO.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/request/template.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/response/NoticeResponseDTO.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/response/template.java
  src/main/java/com/errorCode/pandaOffice/notice/presectation/Controller.java
  src/main/java/com/errorCode/pandaOffice/notice/presectation/NoticeController.java
  src/main/java/com/errorCode/pandaOffice/notice/service/NoticeService.java
  src/main/java/com/errorCode/pandaOffice/notice/service/Service.java
  src/main/resources/application.yml
Labels: 기능구현잇슈, 김민준

#83 [기능 구현] 내 근태 현황 페이지에 필요한 기능들 구현
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/AnnualLeaveCategory.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/OvertimeRecord.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveCategoryRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/AnnualLeaveCategory/response/AnnualLeaveCategoryResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/AnnualLeaveRecord/response/AnnualLeaveRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/AttendanceRecord/response/AttendanceRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/OvertimeRecord/response/OverTimeRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/presectation/AttendanceController.java
  src/main/java/com/errorCode/pandaOffice/attendance/service/AttendanceService.java
Labels: 기능구현잇슈

#91 [기능구현] 공지사항 수정 구현
  DB/Dummy.sql
  http/notice-test.http
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/Notice.java
  src/main/java/com/errorCode/pandaOffice/notice/presectation/NoticeController.java
  src/main/java/com/errorCode/pandaOffice/notice/service/NoticeService.java
Labels: 기능구현잇슈, 김민준

#100 [기능구현] 사원 캘린더 일정 삭제 구현
  chedule.domain.entity
  http/Recruitment.http
  http/Schedule.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/entity/Schedule.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/repository/ScheduleRepository.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/repository/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/ScheduleCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/ScheduleModifyRequest.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/response/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/presectation/Controller.java
  src/main/java/com/errorCode/pandaOffice/schedule/presectation/ScheduleController.java
  src/main/java/com/errorCode/pandaOffice/schedule/service/ScheduleService.java
  src/main/java/com/errorCode/pandaOffice/schedule/service/Service.java
Labels: 기능구현잇슈, 성우현

#90 [기능구현] 사원 캘린더 일정 등록 구현
  chedule.domain.entity
  http/Recruitment.http
  http/Schedule.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/entity/Schedule.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/repository/ScheduleRepository.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/repository/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/ScheduleCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/ScheduleModifyRequest.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/response/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/presectation/Controller.java
  src/main/java/com/errorCode/pandaOffice/schedule/presectation/ScheduleController.java
  src/main/java/com/errorCode/pandaOffice/schedule/service/ScheduleService.java
  src/main/java/com/errorCode/pandaOffice/schedule/service/Service.java
Labels: 기능구현잇슈, 성우현

#97 [기능구현] 사원 캘린더 일정 수정 구현
  chedule.domain.entity
  http/Recruitment.http
  http/Schedule.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/entity/Schedule.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/repository/ScheduleRepository.java
  src/main/java/com/errorCode/pandaOffice/schedule/domain/repository/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/ScheduleCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/ScheduleModifyRequest.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/request/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/errorCode/pandaOffice/schedule/dto/response/template.java
  src/main/java/com/errorCode/pandaOffice/schedule/presectation/Controller.java
  src/main/java/com/errorCode/pandaOffice/schedule/presectation/ScheduleController.java
  src/main/java/com/errorCode/pandaOffice/schedule/service/ScheduleService.java
  src/main/java/com/errorCode/pandaOffice/schedule/service/Service.java
Labels: 기능구현잇슈, 성우현

#102 [기능 구현][관리자 및 사원 기능] 내 연차 내역 페이지에 들어가는 기능 구현 완료
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/AnnualLeaveCategory.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/AnnualLeaveRecord.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/AnnualLeaveCategory/response/AnnualLeaveCategoryResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/AnnualLeaveRecord/response/AnnualLeaveRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/presectation/AttendanceController.java
  src/main/java/com/errorCode/pandaOffice/attendance/service/AttendanceService.java
Labels: 기능구현잇슈

#104 [기능구현] 부서함 정보를 가져오는 api 구현
  DB/Dummy.sql
  http/login-test.http
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalDocument.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DepartmentBox.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DepartmentDocument.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DepartmentBoxRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/ApprovalDocumentDetailResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/ApprovalDocumentListResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/CreateApprovalDocumentRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/UpdateApprovalDocumentRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/departmentBox/request/CreateDepartmentBoxRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/departmentBox/response/DepartmentBoxResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentTemplateController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/DepartmentBoxController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentService.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/DepartmentBoxService.java
Labels: 기능구현잇슈, 편승준

#105 [기능 구현] 연차 캘린더에서 보여주는 내용들을 전달하도록 구현
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/AnnualLeaveRecord/response/AnnualLeaveRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/service/AttendanceService.java
Labels: 기능구현잇슈

#107 [기능구현] 공지사항 삭제 구현
  http/notice-test.http
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/Notice.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/repository/NoticeRepository.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/request/NoticeRequestDTO.java
  src/main/java/com/errorCode/pandaOffice/notice/presectation/NoticeController.java
  src/main/java/com/errorCode/pandaOffice/notice/service/NoticeService.java
Labels: 기능구현잇슈, 김민준

#112 [기능 구현] 연차 조정 페이지에 필요한 기능들 구현
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/AnnualLeaveRecord/response/AnnualLeaveRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/presectation/AttendanceController.java
  src/main/java/com/errorCode/pandaOffice/attendance/service/AttendanceService.java
Labels: 손석현, 기능설계햇슈

#115 [기능구현] 면접자 더미데이터 추가 확장
  DB/recruitment-dummy.sql
  http/Recruitment.http
Labels: 기능구현잇슈, 성우현

#116 [기능구현] 조직도 조회 구현
  http/organization-test.http
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/EmployeePhoto.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/DepartmentRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/EmployeeRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/HobbyRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/JobRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/OrganizationEmployeeImageRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/request/OrganizationRequestDTO.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/response/OrganizationResponseDTO.java
  src/main/java/com/errorCode/pandaOffice/employee/presentation/OrganizationController.java
  src/main/java/com/errorCode/pandaOffice/employee/service/OrganizationService.java
Labels: 기능구현잇슈, 김민준

#120 [기능구현]설문 기능 구현
  DB/WelfareDummy.sql
  http/surveyTest.http
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/Category.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/ReplyRecord.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/Survey.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/SurveyCategory.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/SurveyQuestion.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/ReplyRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/request/CreateSurveyRequest.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/request/ReplyRecordRequest.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/request/UpdateSurveyQuestionRequest.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/request/template.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/ReplyRecordDTO.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/SurveyQuestionDTO.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/SurveyResponse.java
  src/main/java/com/errorCode/pandaOffice/welfare/presectation/SurveyController.java
  src/main/java/com/errorCode/pandaOffice/welfare/service/SurveyService.java
Labels: 기능구현잇슈, 신동우
