Repository ErrorCode-510/PandaOffice_back, pull requests merged in 2024-07, with the labels that each got.

#130 [기능구현] 전자결재 폴더 api 개선
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplate.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/DocumentTemplateRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/ApprovalDocumentFolderResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/UpdateDocumentTemplateStatusRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentTemplateController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentTemplateService.java
Labels: 기능구현잇슈, 편승준

#128 [기타] 사원 및 직급 test 데이터 수정
  DB/Dummy.sql
Labels: 테스트잇슈

#132 [기능수정] 설문 조회 기능 수정
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/ReplyRecord.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/entity/SurveyQuestion.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/ReplyRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/SurveyQuestionRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/SurveyRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/request/ReplyRecordRequest.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/ReplyRecordDTO.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/SurveyDetailsResponse.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/SurveyQuestionDTO.java
  src/main/java/com/errorCode/pandaOffice/welfare/presectation/SurveyController.java
  src/main/java/com/errorCode/pandaOffice/welfare/service/SurveyService.java
Labels: 기능구현잇슈, 신동우

#137 [기능구현] 임시 저장
  http/Recruitment.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/repository/ApplicantRepository.java
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/RecruitmentController.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/RecruitmentService.java
Labels: 성우현

#139 [기능구현] 제작한 API 모든 요청 테스트 완료
  DB/Dummy.sql
  http/attendance.http
  http/login-test.http
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/AnnualLeaveCategory.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/OverTimeAndLatenessRecord.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveCategoryRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveGrantRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AnnualLeaveUsedRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/OverTimeAndLatenessRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/OvertimeRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/AnnualLeaveCategory/response/AnnualLeaveCategoryResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveGrantRecord/response/AnnualLeaveGrantRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/AllLeaveRecordsResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/AnnualLeaveGrantRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/AnnualLeaveRecordCalendarsResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/AnnualLeaveRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/AnnualLeaveUsedRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/CalculateAnnualLeaveRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/CombinedAnnualLeaveResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveUsedRecord/response/AnnualLeaveUsedRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/response/AttendanceAndOvertimeRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/response/AttendanceRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/response/AttendanceSummaryResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/response/CalculatedAttendanceAndOverTimeRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/combined/response/CombinedRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/overTimeAndLatenessRecord/response/CalculatedOverTimeAndLatenessRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/overTimeAndLatenessRecord/response/OverTimeAndLatenessAndAnnualLeaveRequestResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/overTimeAndLatenessRecord/response/OverTimeAndLatenessRecordRequestResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/presectation/AttendanceController.java
  src/main/java/com/errorCode/pandaOffice/attendance/service/AttendanceService.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Job.java
Labels: 기능구현잇슈, 손석현

#135 [기능구현] 사원 정보 조회
  build.gradle
  src/main/java/com/errorCode/pandaOffice/auth/config/SecurityConfig.java
  src/main/java/com/errorCode/pandaOffice/auth/util/EmailUtils.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/CareerHistory.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Department.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/EducationHistory.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/EmployeePhoto.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/FamilyMember.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Job.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/License.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/CareerHistoryRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/EducationHistoryRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/EmployeePhotoRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/FamilyMemberRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/LicenseRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/MemberRepository.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/request/AuthRequest.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/request/ChangePasswordRequest.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/request/EmployeeDTO.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/request/FindIdRequest.java
  src/main/java/com/errorCode/pandaOffice/employee/dto/response/AuthResponse.java
  src/main/java/com/errorCode/pandaOffice/employee/presentation/MemberController.java
  src/main/java/com/errorCode/pandaOffice/employee/service/MemberService.java
  src/main/resources/application.yml
Labels: 기능구현잇슈, 김아연

#141 [기능구현]사원 급여기록 등록
  http/payroll-test.http
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/DeductionCategory.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/DeductionRecord.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/EarningCategory.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/EarningRecord.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/PayrollRecord.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/repository/DeductionCategoryRepository.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/repository/DeductionRepository.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/repository/EarningCategoryRepository.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/repository/EarningRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/repository/PayrollRepository.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/request/PayrollRequest.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/DeductionCategoryResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/DeductionResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/EarningCategoryResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/EarningResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/EmplPayrollResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/PayrollResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/presectation/PayrollController.java
  src/main/java/com/errorCode/pandaOffice/payroll/service/PayrollService.java
Labels: 기능구현잇슈, 이유란, 편승준

#143 #140 feat 사원 직책수당 추가
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Job.java
Labels: 기능구현잇슈, 이유란

#144 [기능 구현] 면접일정 등록 및 상세 조회 Request, Response 수정
  DB/recruitment-dummy.sql
  http/Recruitment.http
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/InterviewScheduleCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/InterviewScheduleModifyRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/ApplicantResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/InterviewScheduleResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/PlaceResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/ScheduleEmployeeResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/RecruitmentController.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/RecruitmentService.java
Labels: 기능구현잇슈, 성우현

#145 [기능구현] 전자결재 양식 등록 DTO 개선
  DB/Dummy.sql
  http/document-test.http
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/CreateTemplateResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentTemplateController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentTemplateService.java
Labels: 기능구현잇슈, 편승준

#147 [기능구현] 사원 정보 수정 구현
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/EmployeePhoto.java
  src/main/java/com/errorCode/pandaOffice/employee/presentation/MemberController.java
  src/main/java/com/errorCode/pandaOffice/employee/service/MemberService.java
Labels: 기능구현잇슈, 김아연

#151 [기능구현] 더미데이터 수정 완료
  DB/Dummy.sql
  http/attendance.http
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/response/AttendanceRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/presectation/AttendanceController.java
  src/main/java/com/errorCode/pandaOffice/attendance/service/AttendanceService.java
Labels: 기능구현잇슈, 손석현

#154 [기능수정] 사원 급여 등록 기능 구현
  http/Recruitment.http
  http/notice-test.http
  http/payroll-test.http
  src/main/java/com/errorCode/pandaOffice/PandaOfficeApplication.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/PayrollRecord.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/repository/template.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/request/PayrollRequest.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/request/template.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/template.java
  src/main/java/com/errorCode/pandaOffice/payroll/presectation/Controller.java
  src/main/java/com/errorCode/pandaOffice/payroll/presectation/PayrollController.java
Labels: 기능구현잇슈, 이유란

#158 [기능구현] 설문 등록 및 조회, 주소 자동 매핑 구현
  http/surveyTest.http
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/SurveyRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/request/ReplyRecordRequest.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/request/SurveyQuestionRequest.java
  src/main/java/com/errorCode/pandaOffice/welfare/dto/response/SurveyResponse.java
  src/main/java/com/errorCode/pandaOffice/welfare/presectation/SurveyController.java
  src/main/java/com/errorCode/pandaOffice/welfare/service/SurveyService.java
Labels: 기능구현잇슈, 신동우

#162 [기능 구현] 캘린더 일정 등록 및 클릭 상세조회 엔티티, 서비스, 리퀘스트 수정
  DB/Dummy.sql
  DB/recruitment-dummy.sql
  http/Recruitment.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/Place.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/InterviewScheduleCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/InterviewScheduleModifyRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/InterviewScheduleResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/PlaceResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/ScheduleEmployeeResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/RecruitmentController.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/RecruitmentService.java
Labels: 기능구현잇슈, 성우현

#160 [기능구현] 공지사항 카테고리 조회 및 등록 로직 수정 구현
  http/notice-test.http
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/EmployeeRepository.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/Notice.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/repository/NoticeRepository.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/request/NoticeRequestDTO.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/response/NoticeResponseDTO.java
  src/main/java/com/errorCode/pandaOffice/notice/presectation/NoticeController.java
  src/main/java/com/errorCode/pandaOffice/notice/service/NoticeService.java
Labels: 기능구현잇슈, 김민준

#164 [기능 설계] 더미데이터 수정 및 추가, 코드 정리
  DB/recruitment-dummy.sql
  http/Recruitment.http
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/Applicant.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/InterviewSchedule.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/entity/Place.java
  src/main/java/com/errorCode/pandaOffice/recruitment/domain/repository/ApplicantRepository.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/InterviewScheduleCreateRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/request/InterviewScheduleModifyRequest.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/ApplicantResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/InterviewScheduleResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/PlaceResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/dto/response/ScheduleEmployeeResponse.java
  src/main/java/com/errorCode/pandaOffice/recruitment/presectation/RecruitmentController.java
  src/main/java/com/errorCode/pandaOffice/recruitment/service/RecruitmentService.java
Labels: 기능구현잇슈, 성우현

#165 [기능구현] 출퇴근 기능구현 완료
  DB/Dummy.sql
  http/attendance.http
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/AnnualLeaveGrantRecord.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/AttendanceRecord.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/entity/OverTimeAndLatenessRecord.java
  src/main/java/com/errorCode/pandaOffice/attendance/domain/repository/AttendanceRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/AllLeaveRecordsResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/request/AttendanceRecordRequest.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/response/AttendanceRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/overTimeAndLatenessRecord/request/overTimeAndLatenessRequest.java
  src/main/java/com/errorCode/pandaOffice/attendance/presectation/AttendanceController.java
  src/main/java/com/errorCode/pandaOffice/attendance/service/AttendanceService.java
Labels: 기능구현잇슈, 손석현

#167 [오류 해결] 시간 파싱 오류 해결
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/response/AttendanceRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/overTimeAndLatenessRecord/response/OverTimeAndLatenessRecordRequestResponse.java
Labels: 버그잇슈, 버그해결햇슈, 손석현

#169 [기능구현] 사원 급여 일괄등록 및 개인조회 구현
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/EarningCategory.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/entity/PayrollRecord.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/repository/EarningRecordRepository.java
  src/main/java/com/errorCode/pandaOffice/payroll/domain/repository/PayrollRepository.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/request/PayrollRequest.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/DeductionResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/EarningResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/PayrollResponse.java
  src/main/java/com/errorCode/pandaOffice/payroll/presectation/PayrollController.java
  src/main/java/com/errorCode/pandaOffice/payroll/service/PayrollService.java
Labels: 기능구현잇슈, 이유란

#170 [기능수정] 사원의 은행정보 Entity 추가
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Account.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
Labels: 기능구현잇슈, 이유란, 김아연, 기능설계햇슈

#168 [기능 구현] 연차 조정 API 제작 완료
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/AllLeaveRecordsResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/attendanceRecord/response/AttendanceRecordResponse.java
Labels: 기능구현잇슈, 손석현

#171 [기능수정]
  DB/Dummy.sql
  http/payroll-test.http
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/PayrollResponse.java
Labels: 테스트잇슈, 이유란

#177 [기능수정] 설문 서비스 및 컨트롤러 로직 수정
  src/main/java/com/errorCode/pandaOffice/welfare/domain/repository/SurveyRepository.java
  src/main/java/com/errorCode/pandaOffice/welfare/presectation/SurveyController.java
  src/main/java/com/errorCode/pandaOffice/welfare/service/SurveyService.java
Labels: 기능구현잇슈, 신동우

#176 [기능구현] 공지사항 조회, 등록 페이지 수정 보완
  http/notice-test.http
  src/main/java/com/errorCode/pandaOffice/notice/domain/entity/Notice.java
  src/main/java/com/errorCode/pandaOffice/notice/domain/repository/NoticeRepository.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/request/NoticeRequestDTO.java
  src/main/java/com/errorCode/pandaOffice/notice/dto/response/NoticeResponseDTO.java
  src/main/java/com/errorCode/pandaOffice/notice/presectation/NoticeController.java
  src/main/java/com/errorCode/pandaOffice/notice/service/NoticeService.java
Labels: 기능구현잇슈, 김민준

#178 [기능구현] 결재 문서 데이터 가져오기
  http/document-test.http
  src/main/java/com/errorCode/pandaOffice/attendance/dto/annualLeaveRecord/response/AnnualLeaveUsedRecordResponse.java
  src/main/java/com/errorCode/pandaOffice/attendance/dto/overTimeAndLatenessRecord/response/OverTimeAndLatenessRecordRequestResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalDocument.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalIntegrateFeature.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLine.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLineTemplate.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/ApprovalLineTemplateOrder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/AutoApprovalLine.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplate.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/entity/DocumentTemplateFolder.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalLineTemplateFolderRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalLineTemplateOrderRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/ApprovalLineTemplateRepository.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/repository/specification/ApprovalDocumentSpecification.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApprovalStatus.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApproveType.java
  src/main/java/com/errorCode/pandaOffice/e_approval/domain/type/ApproveTypeCalculator.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/DepartmentResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/EmployeeResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/JobResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/ApprovalDocumentDetailResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/request/CreateApprovalDocumentRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/request/UpdateApprovalDocumentRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/response/ApprovalDocumentDetailResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocument/response/ApprovalDocumentListResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/ApprovalDocumentFolderResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/ApprovalDocumentTemplateResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/DeleteApprovalDocumentFolderRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/request/CreateApprovalDocumentFolderRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/request/CreateApprovalDocumentTemplateRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/request/UpdateApprovalDocumentTemplateRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/request/UpdateDocumentTemplateRefFolderRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/request/UpdateDocumentTemplateStatusRequest.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/response/ApprovalDocumentFolderResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/response/ApprovalDocumentTemplateResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/response/AutoApprovalLineResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/dto/approvalDocumentTemplate/response/CreateTemplateResponse.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/presectation/ApprovalDocumentTemplateController.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentService.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApprovalDocumentTemplateService.java
  src/main/java/com/errorCode/pandaOffice/e_approval/service/ApproveService.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/repository/EmployeeRepository.java
Labels: 기능구현잇슈, 편승준

#174 [기능구현] 사원 급여관리 구현
  DB/Dummy.sql
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Employee.java
  src/main/java/com/errorCode/pandaOffice/employee/domain/entity/Job.java
  src/main/java/com/errorCode/pandaOffice/payroll/dto/response/PayrollResponse.java
Labels: 기능구현잇슈, 이유란
